#!/bin/bash
# =============================================================================
# K3s Cluster - HAProxy and Keepalived Installation
# =============================================================================
# Installs and configures HAProxy + Keepalived on all master nodes
# for K3s API high availability.
# =============================================================================

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=env.sh
source "${SCRIPT_DIR}/env.sh"

load_inventory

echo "============================================================"
echo " K3s Cluster - HAProxy + Keepalived Installation"
echo "============================================================"
echo ""

# ---------------------------------------------------------------------------
# Generate HAProxy configuration
# ---------------------------------------------------------------------------
generate_haproxy_cfg() {
    local config=""
    config+="# K3s API Server Load Balancer - Generated by install script\n"
    config+="\n"
    config+="global\n"
    config+="    log         /dev/log local0\n"
    config+="    log         /dev/log local1 notice\n"
    config+="    chroot      /var/lib/haproxy\n"
    config+="    pidfile     /var/run/haproxy.pid\n"
    config+="    maxconn     4000\n"
    config+="    user        haproxy\n"
    config+="    group       haproxy\n"
    config+="    daemon\n"
    config+="    stats socket /var/lib/haproxy/stats\n"
    config+="\n"
    config+="defaults\n"
    config+="    mode                    tcp\n"
    config+="    log                     global\n"
    config+="    option                  tcplog\n"
    config+="    option                  dontlognull\n"
    config+="    option                  redispatch\n"
    config+="    retries                 3\n"
    config+="    timeout queue           1m\n"
    config+="    timeout connect         10s\n"
    config+="    timeout client          1m\n"
    config+="    timeout server          1m\n"
    config+="    timeout check           10s\n"
    config+="    maxconn                 3000\n"
    config+="\n"
    config+="listen stats\n"
    config+="    bind *:${HAPROXY_STATS_PORT}\n"
    config+="    mode http\n"
    config+="    stats enable\n"
    config+="    stats uri /stats\n"
    config+="    stats refresh 10s\n"
    config+="    stats auth admin:admin\n"
    config+="\n"
    config+="frontend k3s_api_frontend\n"
    config+="    bind *:${HAPROXY_FRONTEND_PORT}\n"
    config+="    mode tcp\n"
    config+="    option tcplog\n"
    config+="    default_backend k3s_api_backend\n"
    config+="\n"
    config+="backend k3s_api_backend\n"
    config+="    mode tcp\n"
    config+="    option tcp-check\n"
    config+="    balance roundrobin\n"
    config+="    default-server inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 250 maxqueue 256 weight 100\n"
    config+="\n"

    for node_entry in "${MASTER_NODES[@]}"; do
        local hostname ipv4
        hostname=$(parse_node "${node_entry}" "hostname")
        ipv4=$(parse_node "${node_entry}" "ipv4")
        config+="    server ${hostname} ${ipv4}:${K3S_API_PORT} check\n"
    done

    echo -e "${config}"
}

# ---------------------------------------------------------------------------
# Generate Keepalived configuration for a specific node
# ---------------------------------------------------------------------------
generate_keepalived_cfg() {
    local node_index="$1"  # 0-based index
    local state priority

    if [[ ${node_index} -eq 0 ]]; then
        state="MASTER"
        priority=101
    else
        state="BACKUP"
        priority=$((100 - node_index))
    fi

    local config=""
    config+="! Keepalived configuration - Generated by install script\n"
    config+="\n"
    config+="global_defs {\n"
    config+="    router_id K3S_APISERVER\n"
    config+="    script_user root\n"
    config+="    enable_script_security\n"
    config+="}\n"
    config+="\n"
    config+="vrrp_script check_haproxy {\n"
    config+="    script \"/usr/bin/killall -0 haproxy\"\n"
    config+="    interval 2\n"
    config+="    weight 2\n"
    config+="    fall 3\n"
    config+="    rise 2\n"
    config+="}\n"
    config+="\n"
    config+="vrrp_instance K3S_VIP {\n"
    config+="    state ${state}\n"
    config+="    interface ${NETWORK_INTERFACE}\n"
    config+="    virtual_router_id ${KEEPALIVED_ROUTER_ID}\n"
    config+="    priority ${priority}\n"
    config+="    advert_int 1\n"
    config+="\n"
    config+="    authentication {\n"
    config+="        auth_type PASS\n"
    config+="        auth_pass ${KEEPALIVED_AUTH_PASS}\n"
    config+="    }\n"
    config+="\n"
    config+="    virtual_ipaddress {\n"
    config+="        ${K3S_VIP_IPV4}/24 dev ${NETWORK_INTERFACE}\n"
    config+="        ${K3S_VIP_IPV6}/64 dev ${NETWORK_INTERFACE}\n"
    config+="    }\n"
    config+="\n"
    config+="    track_script {\n"
    config+="        check_haproxy\n"
    config+="    }\n"
    config+="}\n"

    echo -e "${config}"
}

# ---------------------------------------------------------------------------
# Install and configure on each master node
# ---------------------------------------------------------------------------
HAPROXY_CFG=$(generate_haproxy_cfg)

node_index=0
for node_entry in "${MASTER_NODES[@]}"; do
    hostname=$(parse_node "${node_entry}" "hostname")
    ipv4=$(parse_node "${node_entry}" "ipv4")

    log_info "Installing HAProxy + Keepalived on ${hostname} (${ipv4})..."

    # Check if packages are installed, install if not
    remote_exec "${ipv4}" "
        if ! rpm -q haproxy &>/dev/null || ! rpm -q keepalived &>/dev/null; then
            transactional-update --non-interactive pkg install haproxy keepalived 2>/dev/null
            echo 'PACKAGES_INSTALLED=true'
        else
            echo 'PACKAGES_INSTALLED=false'
        fi
    "

    # Deploy HAProxy config
    remote_exec "${ipv4}" "mkdir -p /etc/haproxy"
    echo -e "${HAPROXY_CFG}" | remote_exec "${ipv4}" "cat > /etc/haproxy/haproxy.cfg"
    log_success "  HAProxy config deployed"

    # Deploy Keepalived config
    KEEPALIVED_CFG=$(generate_keepalived_cfg ${node_index})
    remote_exec "${ipv4}" "mkdir -p /etc/keepalived"
    echo -e "${KEEPALIVED_CFG}" | remote_exec "${ipv4}" "cat > /etc/keepalived/keepalived.conf"
    log_success "  Keepalived config deployed (priority: $((101 - node_index)))"

    # Enable and start services
    remote_exec "${ipv4}" "
        systemctl enable haproxy 2>/dev/null || true
        systemctl enable keepalived 2>/dev/null || true
        systemctl restart haproxy 2>/dev/null || true
        systemctl restart keepalived 2>/dev/null || true
    "
    log_success "  Services enabled and started"

    echo ""
    ((node_index++))
done

# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------
log_info "Verifying HAProxy and Keepalived..."
echo ""

sleep 3

# Check VIP assignment
FIRST_MASTER_IPV4=$(parse_node "${MASTER_NODES[0]}" "ipv4")
VIP_CHECK=$(remote_exec "${FIRST_MASTER_IPV4}" "ip addr show ${NETWORK_INTERFACE} | grep '${K3S_VIP_IPV4}'" 2>/dev/null || echo "NOT FOUND")

if [[ "${VIP_CHECK}" != "NOT FOUND" ]]; then
    log_success "VIP ${K3S_VIP_IPV4} is active on $(parse_node "${MASTER_NODES[0]}" "hostname")"
else
    log_warn "VIP not yet active on first master. Check keepalived logs."
fi

# Check HAProxy is listening
for node_entry in "${MASTER_NODES[@]}"; do
    hostname=$(parse_node "${node_entry}" "hostname")
    ipv4=$(parse_node "${node_entry}" "ipv4")

    if remote_exec "${ipv4}" "ss -tlnp | grep -q ':${HAPROXY_FRONTEND_PORT}'" 2>/dev/null; then
        log_success "  ${hostname}: HAProxy listening on port ${HAPROXY_FRONTEND_PORT}"
    else
        log_warn "  ${hostname}: HAProxy NOT listening on port ${HAPROXY_FRONTEND_PORT}"
    fi
done

echo ""
echo "============================================================"
log_success "HAProxy + Keepalived installation complete."
echo ""
echo "  VIP: ${K3S_VIP_IPV4} / ${K3S_VIP_IPV6}"
echo "  HAProxy stats: http://<master-ip>:${HAPROXY_STATS_PORT}/stats"
echo "  Note: Backend servers will show as DOWN until K3s is installed."
echo "============================================================"
