/* K3s Configuration Generator - Templates (v2.0.0)
 *
 * All Jinja2/Nunjucks templates for configuration file generation.
 * These mirror the templates in templates/jinja2/ but are embedded
 * for client-side rendering in the browser.
 */

// eslint-disable-next-line no-unused-vars
var TEMPLATES = {

    // =========================================================================
    // HAProxy Configuration
    // =========================================================================
    "haproxy/haproxy.cfg": `# K3s API Server Load Balancer
# Generated by K3s Configuration Generator v2.0.0
# Deploy to /etc/haproxy/haproxy.cfg on all master nodes

global
    log         /dev/log local0
    log         /dev/log local1 notice
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon
    stats socket /var/lib/haproxy/stats

defaults
    mode                    tcp
    log                     global
    option                  tcplog
    option                  dontlognull
    option                  redispatch
    retries                 3
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout check           10s
    maxconn                 3000

#---------------------------------------------------------------------
# Statistics - accessible at http://<master-ip>:{{ haproxy.stats_port }}/stats
#---------------------------------------------------------------------
listen stats
    bind *:{{ haproxy.stats_port }}
    mode http
    stats enable
    stats uri /stats
    stats refresh 10s
    stats auth {{ haproxy.stats_user }}:{{ haproxy.stats_password }}

#---------------------------------------------------------------------
# K3s API Server Frontend
#---------------------------------------------------------------------
frontend k3s_api_frontend
    bind *:{{ haproxy.frontend_port }}
    mode tcp
    option tcplog
    default_backend k3s_api_backend

#---------------------------------------------------------------------
# K3s API Server Backend
#---------------------------------------------------------------------
backend k3s_api_backend
    mode tcp
    option tcp-check
    balance roundrobin
    default-server inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 250 maxqueue 256 weight 100

{% for master in masters %}
    server {{ master.hostname }} {{ master.ipv4 }}:{{ k3s.api_port }} check
{% endfor %}
`,

    // =========================================================================
    // Keepalived Configuration (per-node)
    // =========================================================================
    "keepalived.conf": `! Keepalived configuration for {{ node.hostname }}
! Generated by K3s Configuration Generator v2.0.0
! Deploy to /etc/keepalived/keepalived.conf

global_defs {
    router_id K3S_APISERVER
    script_user root
    enable_script_security
}

vrrp_script check_haproxy {
    script "/usr/bin/killall -0 haproxy"
    interval {{ keepalived.check_interval }}
    weight 2
    fall {{ keepalived.fall }}
    rise {{ keepalived.rise }}
}

vrrp_instance K3S_VIP {
    state {{ "MASTER" if node_index == 0 else "BACKUP" }}
    interface {{ resolved_interface }}
    virtual_router_id {{ keepalived.router_id }}
    priority {{ 101 - node_index }}
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass {{ keepalived.auth_pass }}
    }

    virtual_ipaddress {
        {{ vip.ipv4 }}/{{ network.subnet_mask_ipv4 }} dev {{ resolved_interface }}
{% if network.ipv6_enabled %}
        {{ vip.ipv6 }}/{{ network.subnet_mask_ipv6 }} dev {{ resolved_interface }}
{% endif %}
    }

    track_script {
        check_haproxy
    }
}
`,

    // =========================================================================
    // K3s Server Configuration (per-node)
    // =========================================================================
    "k3s-server.yaml": `# K3s Server Configuration for {{ node.hostname }}
# Generated by K3s Configuration Generator v2.0.0
# Deploy to /etc/rancher/k3s/config.yaml
{% if node_index == 0 %}

# First server - initializes the cluster
cluster-init: true
{% else %}

# Additional server - joins existing cluster
server: "https://{{ masters[0].ipv4 }}:{{ k3s.api_port }}"
{% endif %}

# Cluster authentication token
token: "{{ k3s.token or 'GENERATE_TOKEN_AT_DEPLOY_TIME' }}"

# TLS Subject Alternative Names
tls-san:
  - "{{ vip.ipv4 }}"
{% if network.ipv6_enabled %}
  - "{{ vip.ipv6 }}"
{% endif %}
  - "{{ vip.hostname }}.{{ network.domain }}"
{% for master in masters %}
  - "{{ master.hostname }}.{{ network.domain }}"
  - "{{ master.hostname }}"
  - "{{ master.ipv4 }}"
{% endfor %}

# Node networking
{% if network.ipv6_enabled %}
node-ip: "{{ node.ipv4 }},{{ node.ipv6 }}"
{% else %}
node-ip: "{{ node.ipv4 }}"
{% endif %}
advertise-address: "{{ node.ipv4 }}"

# Cluster CIDR
{% if network.ipv6_enabled %}
cluster-cidr: "{{ k3s.cluster_cidr_v4 }},{{ k3s.cluster_cidr_v6 }}"
service-cidr: "{{ k3s.service_cidr_v4 }},{{ k3s.service_cidr_v6 }}"
{% else %}
cluster-cidr: "{{ k3s.cluster_cidr_v4 }}"
service-cidr: "{{ k3s.service_cidr_v4 }}"
{% endif %}

# Disabled default components
disable:
{% for component in k3s.disable %}
  - "{{ component }}"
{% endfor %}

# Kubeconfig
write-kubeconfig-mode: "0644"

# etcd
etcd-expose-metrics: true

# API server arguments
kube-apiserver-arg:
  - "advertise-address={{ node.ipv4 }}"
`,

    // =========================================================================
    // K3s Agent Configuration (per-node)
    // =========================================================================
    "k3s-agent.yaml": `# K3s Agent Configuration for {{ node.hostname }}
# Generated by K3s Configuration Generator v2.0.0
# Deploy to /etc/rancher/k3s/config.yaml

# Connect to K3s API via the VIP (HAProxy load balanced)
server: "https://{{ vip.ipv4 }}:{{ haproxy.frontend_port }}"

# Cluster authentication token
token: "{{ k3s.token or 'GENERATE_TOKEN_AT_DEPLOY_TIME' }}"

# Node networking
{% if network.ipv6_enabled %}
node-ip: "{{ node.ipv4 }},{{ node.ipv6 }}"
{% else %}
node-ip: "{{ node.ipv4 }}"
{% endif %}

# Node labels
node-label:
  - "node-role.kubernetes.io/worker=worker"
`,

    // =========================================================================
    // DHCPv4 Static Leases
    // =========================================================================
    "network/dhcpd4-leases.conf": `# ISC DHCP Server - DHCPv4 Static Leases for K3s Cluster
# Generated by K3s Configuration Generator v2.0.0
# Include in dhcpd.conf: include "/etc/dhcp/k3s-leases.conf";

group k3s-cluster {
    option domain-name "{{ network.domain }}";
    option domain-name-servers {{ network.dns_servers[0] }};
    option routers {{ network.gateway_ipv4 }};
    default-lease-time {{ dhcp.default_lease_time }};
    max-lease-time {{ dhcp.max_lease_time }};

    # Master Nodes
{% for master in masters %}
    host {{ master.hostname }} {
        hardware ethernet {{ master.mac }};
        fixed-address {{ master.ipv4 }};
        option host-name "{{ master.hostname }}";
    }

{% endfor %}
    # Worker Nodes
{% for worker in workers %}
    host {{ worker.hostname }} {
        hardware ethernet {{ worker.mac }};
        fixed-address {{ worker.ipv4 }};
        option host-name "{{ worker.hostname }}";
    }

{% endfor %}
}

# VIP Reservation (prevent dynamic assignment)
host k3s-vip-reservation {
    hardware ethernet 00:00:00:00:00:00;
    fixed-address {{ vip.ipv4 }};
    option host-name "{{ vip.hostname }}";
}
`,

    // =========================================================================
    // DHCPv6 Static Leases
    // =========================================================================
    "network/dhcpd6-leases.conf": `# ISC DHCP Server - DHCPv6 Static Leases for K3s Cluster
# Generated by K3s Configuration Generator v2.0.0
# Include in dhcpd6.conf: include "/etc/dhcp/k3s-leases6.conf";
{% if network.ipv6_enabled %}

group k3s-cluster-v6 {
    option dhcp6.domain-search "{{ network.domain }}";

    # Master Nodes
{% for master in masters %}
    host {{ master.hostname }} {
        host-identifier option dhcp6.client-id {{ master.duid }};
        fixed-address6 {{ master.ipv6 }};
    }

{% endfor %}
    # Worker Nodes
{% for worker in workers %}
    host {{ worker.hostname }} {
        host-identifier option dhcp6.client-id {{ worker.duid }};
        fixed-address6 {{ worker.ipv6 }};
    }

{% endfor %}
}
{% endif %}
`,

    // =========================================================================
    // dnsmasq Static Leases
    // =========================================================================
    "network/dnsmasq-leases.conf": `# dnsmasq Static DHCP Leases for K3s Cluster
# Generated by K3s Configuration Generator v2.0.0

# DHCPv4 Static Leases
{% for master in masters %}
dhcp-host={{ master.mac }},{{ master.ipv4 }},{{ master.hostname }},infinite
{% endfor %}
{% for worker in workers %}
dhcp-host={{ worker.mac }},{{ worker.ipv4 }},{{ worker.hostname }},infinite
{% endfor %}
{% if network.ipv6_enabled and (network.ipv6_mode == "dhcpv6" or network.ipv6_mode == "both") %}

# DHCPv6 Static Leases
{% for master in masters %}
dhcp-host=id:{{ master.duid }},[{{ master.ipv6 }}],{{ master.hostname }},infinite
{% endfor %}
{% for worker in workers %}
dhcp-host=id:{{ worker.duid }},[{{ worker.ipv6 }}],{{ worker.hostname }},infinite
{% endfor %}
{% endif %}

# DNS Records (A)
address=/{{ vip.hostname }}.{{ network.domain }}/{{ vip.ipv4 }}
{% for master in masters %}
address=/{{ master.hostname }}.{{ network.domain }}/{{ master.ipv4 }}
{% endfor %}
{% for worker in workers %}
address=/{{ worker.hostname }}.{{ network.domain }}/{{ worker.ipv4 }}
{% endfor %}
{% if network.ipv6_enabled %}

# DNS Records (AAAA)
address=/{{ vip.hostname }}.{{ network.domain }}/{{ vip.ipv6 }}
{% for master in masters %}
address=/{{ master.hostname }}.{{ network.domain }}/{{ master.ipv6 }}
{% endfor %}
{% for worker in workers %}
address=/{{ worker.hostname }}.{{ network.domain }}/{{ worker.ipv6 }}
{% endfor %}
{% endif %}
`,

    // =========================================================================
    // /etc/hosts
    // =========================================================================
    "network/hosts": `# /etc/hosts entries for K3s Cluster
# Generated by K3s Configuration Generator v2.0.0
# Append to /etc/hosts on all cluster nodes.

# K3s API Virtual IP
{{ vip.ipv4 }}    {{ vip.hostname }}.{{ network.domain }} {{ vip.hostname }}
{% if network.ipv6_enabled %}
{{ vip.ipv6 }}    {{ vip.hostname }}.{{ network.domain }} {{ vip.hostname }}
{% endif %}

# Master nodes
{% for master in masters %}
{{ master.ipv4 }}    {{ master.hostname }}.{{ network.domain }} {{ master.hostname }}
{% if network.ipv6_enabled %}
{{ master.ipv6 }}    {{ master.hostname }}.{{ network.domain }} {{ master.hostname }}
{% endif %}
{% endfor %}

# Worker nodes
{% for worker in workers %}
{{ worker.ipv4 }}    {{ worker.hostname }}.{{ network.domain }} {{ worker.hostname }}
{% if network.ipv6_enabled %}
{{ worker.ipv6 }}    {{ worker.hostname }}.{{ network.domain }} {{ worker.hostname }}
{% endif %}
{% endfor %}
`,

    // =========================================================================
    // Sysctl Configuration
    // =========================================================================
    "os/sysctl-k3s.conf": `# Kernel parameters for K3s nodes
# Generated by K3s Configuration Generator v2.0.0
# Deploy to /etc/sysctl.d/90-k3s.conf

# IPv4 forwarding
net.ipv4.ip_forward = 1
{% if network.ipv6_enabled %}

# IPv6 forwarding
net.ipv6.conf.all.forwarding = 1

# CRITICAL: Accept Router Advertisements even with forwarding enabled.
# Without this (value=2), enabling forwarding causes the kernel to ignore RAs,
# which breaks SLAAC and DHCPv6 address acquisition.
net.ipv6.conf.all.accept_ra = 2
net.ipv6.conf.default.accept_ra = 2
{% endif %}

# Bridge networking
net.bridge.bridge-nf-call-iptables = 1
{% if network.ipv6_enabled %}
net.bridge.bridge-nf-call-ip6tables = 1
{% endif %}

# Increase inotify limits
fs.inotify.max_user_instances = 524288
fs.inotify.max_user_watches = 524288

# Increase conntrack table size
net.netfilter.nf_conntrack_max = 131072

# HAProxy non-local bind (master nodes only)
net.ipv4.ip_nonlocal_bind = 1
{% if network.ipv6_enabled %}
net.ipv6.ip_nonlocal_bind = 1
{% endif %}
`,

    // =========================================================================
    // SSH Configuration
    // =========================================================================
    "os/ssh-authorized-keys": `# SSH Authorized Keys for K3s Cluster Nodes
# Generated by K3s Configuration Generator v2.0.0
# Deploy to /root/.ssh/authorized_keys on all nodes
#
{% if ssh.github_users | length > 0 %}
# Keys will also be fetched at deploy time from:
{% for user in ssh.github_users %}
#   https://github.com/{{ user }}.keys
{% endfor %}
{% endif %}
# --- Configured keys ---
{% for key in ssh.authorized_keys %}
{{ key }}
{% endfor %}
`,

    "os/sshd-hardening.conf": `# SSH Hardening for K3s Cluster Nodes
# Generated by K3s Configuration Generator v2.0.0
# Deploy to /etc/ssh/sshd_config.d/10-k3s-hardening.conf
{% if ssh.disable_password_auth %}
PasswordAuthentication no
{% else %}
PasswordAuthentication yes
{% endif %}
ChallengeResponseAuthentication no
PubkeyAuthentication yes
PermitRootLogin prohibit-password
MaxAuthTries 3
ClientAliveInterval 300
ClientAliveCountMax 2
Port {{ ssh.port }}
`,

    // =========================================================================
    // Router / Firewall Checklist
    // =========================================================================
    "network/router-checklist.md": `# Router & Firewall Configuration Checklist
# Generated by K3s Configuration Generator v2.0.0
# Cluster domain: {{ network.domain }}

## 1. DHCPv4 Static Leases

Reserve these MAC-to-IPv4 mappings on your DHCP server:

| Hostname | MAC Address | IPv4 Address |
|----------|-------------|--------------|
{% for master in masters %}
| {{ master.hostname }} | {{ master.mac }} | {{ master.ipv4 }} |
{% endfor %}
{% for worker in workers %}
| {{ worker.hostname }} | {{ worker.mac }} | {{ worker.ipv4 }} |
{% endfor %}

**IMPORTANT:** Reserve VIP {{ vip.ipv4 }} ({{ vip.hostname }}) — must NOT be in the DHCP dynamic range.
{% if network.ipv6_enabled and (network.ipv6_mode == "dhcpv6" or network.ipv6_mode == "both") %}

## 2. DHCPv6 Static Leases (mode: {{ network.ipv6_mode }})

Reserve these DUID-to-IPv6 mappings on your DHCPv6 server:

| Hostname | DUID | IPv6 Address |
|----------|------|--------------|
{% for master in masters %}
| {{ master.hostname }} | {{ master.duid }} | {{ master.ipv6 }} |
{% endfor %}
{% for worker in workers %}
| {{ worker.hostname }} | {{ worker.duid }} | {{ worker.ipv6 }} |
{% endfor %}
{% endif %}
{% if network.ipv6_enabled %}

## 3. Router Advertisements
{% if network.ipv6_mode == "slaac" or network.ipv6_mode == "both" %}

- Enable RA on LAN interface
- Set AdvAutonomous ON (A=1) for SLAAC address generation
{% if network.ipv6_mode == "both" %}
- Set AdvManagedFlag ON (M=1) for DHCPv6 address assignment
{% endif %}
- Set AdvOtherConfigFlag ON (O=1) for DNS/NTP via DHCPv6
{% elif network.ipv6_mode == "dhcpv6" %}

- Enable RA on LAN interface (required for default gateway even with DHCPv6)
- Set AdvAutonomous OFF (A=0) — disable SLAAC
- Set AdvManagedFlag ON (M=1) — use DHCPv6 for addresses
- Set AdvOtherConfigFlag ON (O=1) — use DHCPv6 for DNS/NTP
{% endif %}
{% endif %}

## 4. DNS Records

### Forward Records
| Hostname | A Record |{% if network.ipv6_enabled %} AAAA Record |{% endif %}

|----------|----------|{% if network.ipv6_enabled %}-------------|{% endif %}

| {{ vip.hostname }}.{{ network.domain }} | {{ vip.ipv4 }} |{% if network.ipv6_enabled %} {{ vip.ipv6 }} |{% endif %}

{% for master in masters %}
| {{ master.hostname }}.{{ network.domain }} | {{ master.ipv4 }} |{% if network.ipv6_enabled %} {{ master.ipv6 }} |{% endif %}

{% endfor %}
{% for worker in workers %}
| {{ worker.hostname }}.{{ network.domain }} | {{ worker.ipv4 }} |{% if network.ipv6_enabled %} {{ worker.ipv6 }} |{% endif %}

{% endfor %}

## 5. Firewall Rules

### Ports to Open Between Cluster Nodes

| Port | Protocol | Purpose | Direction |
|------|----------|---------|-----------|
| {{ k3s.api_port }} | TCP | K3s API Server | All -> Masters |
| 2379-2380 | TCP | etcd peer/client | Masters <-> Masters |
| 10250 | TCP | Kubelet API | All <-> All |
| 8472 | UDP | Flannel VXLAN | All <-> All |
| 30000-32767 | TCP/UDP | NodePort Services | External -> All |
| 112 | VRRP (IP proto) | Keepalived VIP failover | Masters <-> Masters |
| {{ haproxy.stats_port }} | TCP | HAProxy Stats | Admin -> Masters |
| {{ ssh.port }} | TCP | SSH | Admin -> All |
{% if network.ipv6_enabled %}

### ICMPv6 (CRITICAL)

**Never block ICMPv6 entirely.** IPv6 depends on it for:
- Neighbor Discovery (replaces ARP)
- Router Solicitation/Advertisement
- Path MTU Discovery
- Duplicate Address Detection

At minimum allow ICMPv6 types: 133 (RS), 134 (RA), 135 (NS), 136 (NA), 137 (Redirect).
{% endif %}

## 6. Network Services Checklist

- [ ] DHCPv4 server with static leases for all nodes
- [ ] DNS server with A records for all nodes + VIP
{% if network.ipv6_enabled %}
{% if network.ipv6_mode == "dhcpv6" or network.ipv6_mode == "both" %}
- [ ] DHCPv6 server with static leases (DUID-based) for all nodes
{% endif %}
- [ ] DNS server with AAAA records for all nodes + VIP
- [ ] Router Advertisements enabled on LAN interface
{% endif %}
- [ ] VIP address ({{ vip.ipv4 }}) excluded from DHCP dynamic range
- [ ] Firewall rules allowing inter-node cluster traffic
- [ ] NTP server accessible from cluster nodes
`,

    // =========================================================================
    // Variables YAML (for reference / use with Python generator)
    // =========================================================================
    "variables.yaml": `# K3s Cluster Variables
# Generated by K3s Configuration Generator v2.0.0
# Use with: python3 generate.py --vars variables.yaml

os:
  distribution: "{{ os.distribution }}"

network:
  interface: "{{ network.interface }}"
  domain: "{{ network.domain }}"
  dns_servers:
    - "{{ network.dns_servers[0] }}"
  gateway_ipv4: "{{ network.gateway_ipv4 }}"
  subnet_mask_ipv4: {{ network.subnet_mask_ipv4 }}
  subnet_mask_ipv6: {{ network.subnet_mask_ipv6 }}
  ipv6_mode: "{{ network.ipv6_mode }}"
  ipv6_enabled: {{ network.ipv6_enabled }}

vip:
  ipv4: "{{ vip.ipv4 }}"
{% if network.ipv6_enabled %}
  ipv6: "{{ vip.ipv6 }}"
{% endif %}
  hostname: "{{ vip.hostname }}"

masters:
{% for master in masters %}
  - hostname: "{{ master.hostname }}"
    ipv4: "{{ master.ipv4 }}"
{% if network.ipv6_enabled %}
    ipv6: "{{ master.ipv6 }}"
{% endif %}
    mac: "{{ master.mac }}"
{% if network.ipv6_enabled %}
    duid: "{{ master.duid }}"
{% endif %}
{% if master.net_interface %}
    net_interface: "{{ master.net_interface }}"
{% endif %}
{% if master.os_disk %}
    os_disk: "{{ master.os_disk }}"
{% endif %}
{% endfor %}

workers:
{% for worker in workers %}
  - hostname: "{{ worker.hostname }}"
    ipv4: "{{ worker.ipv4 }}"
{% if network.ipv6_enabled %}
    ipv6: "{{ worker.ipv6 }}"
{% endif %}
    mac: "{{ worker.mac }}"
{% if network.ipv6_enabled %}
    duid: "{{ worker.duid }}"
{% endif %}
{% if worker.net_interface %}
    net_interface: "{{ worker.net_interface }}"
{% endif %}
{% if worker.os_disk %}
    os_disk: "{{ worker.os_disk }}"
{% endif %}
{% endfor %}

k3s:
  version: "{{ k3s.version }}"
  token: "{{ k3s.token }}"
  api_port: {{ k3s.api_port }}
  disable:
{% for component in k3s.disable %}
    - "{{ component }}"
{% endfor %}
  cluster_cidr_v4: "{{ k3s.cluster_cidr_v4 }}"
{% if network.ipv6_enabled %}
  cluster_cidr_v6: "{{ k3s.cluster_cidr_v6 }}"
{% endif %}
  service_cidr_v4: "{{ k3s.service_cidr_v4 }}"
{% if network.ipv6_enabled %}
  service_cidr_v6: "{{ k3s.service_cidr_v6 }}"
{% endif %}

haproxy:
  frontend_port: {{ haproxy.frontend_port }}
  stats_port: {{ haproxy.stats_port }}
  stats_user: "{{ haproxy.stats_user }}"
  stats_password: "{{ haproxy.stats_password }}"

keepalived:
  router_id: {{ keepalived.router_id }}
  auth_pass: "{{ keepalived.auth_pass }}"
  check_interval: 2
  fall: 3
  rise: 2

dhcp:
  default_lease_time: {{ dhcp.default_lease_time }}
  max_lease_time: {{ dhcp.max_lease_time }}

ssh:
  user: "{{ ssh.user }}"
  port: {{ ssh.port }}
  github_users:
{% for user in ssh.github_users %}
    - "{{ user }}"
{% endfor %}
  authorized_keys:
{% for key in ssh.authorized_keys %}
    - "{{ key }}"
{% endfor %}
  disable_password_auth: {{ ssh.disable_password_auth }}

storage:
  disk_layout: "{{ storage.disk_layout }}"
  os_disk: "{{ storage.os_disk }}"
  os_root_size: "{{ storage.os_root_size }}"
  rancher_size: "{{ storage.rancher_size }}"
  data_disk: "{{ storage.data_disk }}"
  storage_disk: "{{ storage.storage_disk }}"
  storage_size: "{{ storage.storage_size }}"
  provider: "{{ storage.provider }}"
  longhorn:
    version: "{{ storage.longhorn.version }}"
    replica_count: {{ storage.longhorn.replica_count }}
    data_path: "{{ storage.longhorn.data_path }}"
    default_class: {{ storage.longhorn.default_class }}
    ui_enabled: {{ storage.longhorn.ui_enabled }}
  local_path:
    data_path: "{{ storage.local_path.data_path }}"
    default_class: {{ storage.local_path.default_class }}
`,

    // =========================================================================
    // Disk Partitioning - Single Root (AutoYaST) - per-node
    // =========================================================================
    "os/disk-single-root.xml": `<!-- AutoYaST Disk Partitioning: Single Root -->
<!-- Node: {{ node.hostname }} -->
<!-- Layout: Single Btrfs root partition with OS-managed subvolumes -->

<partitioning config:type="list">
  <drive>
    <device>{{ resolved_os_disk }}</device>
    <initialize config:type="boolean">true</initialize>
    <use>all</use>
    <partitions config:type="list">
      <partition>
        <mount>/boot/efi</mount>
        <size>512M</size>
        <filesystem config:type="symbol">vfat</filesystem>
      </partition>
      <partition>
        <mount>/</mount>
        <size>max</size>
        <filesystem config:type="symbol">btrfs</filesystem>
      </partition>
    </partitions>
  </drive>
</partitioning>
`,

    // =========================================================================
    // Disk Partitioning - Multi-Partition (AutoYaST) - per-node
    // =========================================================================
    "os/disk-multipart.xml": `<!-- AutoYaST Disk Partitioning: Multi-Partition (Single Disk) -->
<!-- Node: {{ node.hostname }} -->
<!-- Layout: EFI + Root (Btrfs) + Rancher (XFS) + Storage (XFS) -->

<partitioning config:type="list">
  <drive>
    <device>{{ resolved_os_disk }}</device>
    <initialize config:type="boolean">true</initialize>
    <use>all</use>
    <partitions config:type="list">
      <partition>
        <mount>/boot/efi</mount>
        <size>512M</size>
        <filesystem config:type="symbol">vfat</filesystem>
      </partition>
      <partition>
        <mount>/</mount>
        <size>{{ storage.os_root_size }}</size>
        <filesystem config:type="symbol">btrfs</filesystem>
      </partition>
      <partition>
        <mount>/var/lib/rancher</mount>
        <size>{{ storage.rancher_size }}</size>
        <filesystem config:type="symbol">xfs</filesystem>
      </partition>
{% if storage.provider == "longhorn" %}
      <partition>
        <mount>{{ storage.longhorn.data_path }}</mount>
        <size>{{ storage.storage_size }}</size>
        <filesystem config:type="symbol">xfs</filesystem>
      </partition>
{% elif storage.provider == "local-path" %}
      <partition>
        <mount>{{ storage.local_path.data_path }}</mount>
        <size>{{ storage.storage_size }}</size>
        <filesystem config:type="symbol">xfs</filesystem>
      </partition>
{% endif %}
    </partitions>
  </drive>
</partitioning>
`,

    // =========================================================================
    // Disk Partitioning - Multi-Disk (AutoYaST) - per-node
    // =========================================================================
    "os/disk-multidisk.xml": `<!-- AutoYaST Disk Partitioning: Multi-Disk -->
<!-- Node: {{ node.hostname }} -->
<!-- Layout: Disk 1 (OS) + Disk 2 (K3s data) + Disk 3 (Storage) -->

<partitioning config:type="list">
  <!-- Disk 1: Operating System -->
  <drive>
    <device>{{ resolved_os_disk }}</device>
    <initialize config:type="boolean">true</initialize>
    <use>all</use>
    <partitions config:type="list">
      <partition>
        <mount>/boot/efi</mount>
        <size>512M</size>
        <filesystem config:type="symbol">vfat</filesystem>
      </partition>
      <partition>
        <mount>/</mount>
        <size>max</size>
        <filesystem config:type="symbol">btrfs</filesystem>
      </partition>
    </partitions>
  </drive>

  <!-- Disk 2: K3s Data -->
  <drive>
    <device>{{ storage.data_disk }}</device>
    <initialize config:type="boolean">true</initialize>
    <use>all</use>
    <partitions config:type="list">
      <partition>
        <mount>/var/lib/rancher</mount>
        <size>max</size>
        <filesystem config:type="symbol">xfs</filesystem>
      </partition>
    </partitions>
  </drive>

{% if storage.provider == "longhorn" %}
  <!-- Disk 3: Longhorn Persistent Storage -->
  <drive>
    <device>{{ storage.storage_disk }}</device>
    <initialize config:type="boolean">true</initialize>
    <use>all</use>
    <partitions config:type="list">
      <partition>
        <mount>{{ storage.longhorn.data_path }}</mount>
        <size>max</size>
        <filesystem config:type="symbol">xfs</filesystem>
      </partition>
    </partitions>
  </drive>
{% elif storage.provider == "local-path" %}
  <!-- Disk 3: Local-Path Persistent Storage -->
  <drive>
    <device>{{ storage.storage_disk }}</device>
    <initialize config:type="boolean">true</initialize>
    <use>all</use>
    <partitions config:type="list">
      <partition>
        <mount>{{ storage.local_path.data_path }}</mount>
        <size>max</size>
        <filesystem config:type="symbol">xfs</filesystem>
      </partition>
    </partitions>
  </drive>
{% endif %}
</partitioning>
`,

    // =========================================================================
    // Disk Ignition Config - per-node
    // =========================================================================
    "os/disk-ignition.json": `{
  "comment": "Ignition disk configuration for {{ node.hostname }} ({{ storage.disk_layout }})",
  "storage": {
    "disks": [
      {
        "device": "{{ resolved_os_disk }}",
        "wipeTable": true,
        "partitions": [
          {"label": "efi", "sizeMiB": 512, "typeGuid": "C12A7328-F81F-11D2-BA4B-00A0C93EC93B"}{% if storage.disk_layout == "single-root" %},
          {"label": "root", "sizeMiB": 0}
{% elif storage.disk_layout == "single-disk-multipart" %},
          {"label": "root", "sizeMiB": {{ storage.os_root_size_mib }}},
          {"label": "rancher", "sizeMiB": {{ storage.rancher_size_mib }}}{% if storage.provider != "none" %},
          {"label": "storage", "sizeMiB": 0}{% endif %}

{% endif %}
        ]
      }{% if storage.disk_layout == "multi-disk" %},
      {"device": "{{ storage.data_disk }}", "wipeTable": true, "partitions": [{"label": "rancher", "sizeMiB": 0}]}{% if storage.provider != "none" %},
      {"device": "{{ storage.storage_disk }}", "wipeTable": true, "partitions": [{"label": "storage", "sizeMiB": 0}]}{% endif %}
{% endif %}

    ],
    "filesystems": [
      {"device": "/dev/disk/by-partlabel/efi", "format": "vfat", "path": "/boot/efi"},
      {"device": "/dev/disk/by-partlabel/root", "format": "btrfs", "path": "/"}{% if storage.disk_layout != "single-root" %},
      {"device": "/dev/disk/by-partlabel/rancher", "format": "xfs", "path": "/var/lib/rancher"}{% endif %}{% if storage.provider == "longhorn" and storage.disk_layout != "single-root" %},
      {"device": "/dev/disk/by-partlabel/storage", "format": "xfs", "path": "{{ storage.longhorn.data_path }}"}{% elif storage.provider == "local-path" and storage.disk_layout != "single-root" %},
      {"device": "/dev/disk/by-partlabel/storage", "format": "xfs", "path": "{{ storage.local_path.data_path }}"}{% endif %}

    ]
  }
}
`,

    // =========================================================================
    // Longhorn Helm Values
    // =========================================================================
    "storage/longhorn-values.yaml": `# Longhorn Helm Values
# Deploy with: helm install longhorn longhorn/longhorn -n longhorn-system --create-namespace -f longhorn-values.yaml

defaultSettings:
  defaultReplicaCount: {{ storage.longhorn.replica_count }}
  defaultDataPath: "{{ storage.longhorn.data_path }}"
  createDefaultDiskLabeledNodes: true
  storageOverProvisioningPercentage: 200
  storageMinimalAvailablePercentage: 15
  replicaAutoBalance: "best-effort"

persistence:
  defaultClass: {{ storage.longhorn.default_class }}
  defaultClassReplicaCount: {{ storage.longhorn.replica_count }}
  defaultFsType: "ext4"
  reclaimPolicy: "Delete"

csi:
  kubeletRootDir: "/var/lib/kubelet"

longhornUI:
  enabled: {{ storage.longhorn.ui_enabled }}
  replicas: 1

ingress:
  enabled: false
`,

    // =========================================================================
    // Local-Path StorageClass
    // =========================================================================
    "storage/storageclass-local-path.yaml": `# Local-Path Provisioner Configuration
# Apply with: kubectl apply -f storageclass-local-path.yaml

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-path-config
  namespace: kube-system
data:
  config.json: |-
    {
      "nodePathMap": [
        {
          "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
          "paths": ["{{ storage.local_path.data_path }}"]
        }
      ]
    }

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ storage.local_path.default_class }}"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
`
};
