/* K3s Configuration Generator - Templates
 *
 * All Jinja2/Nunjucks templates for configuration file generation.
 * These mirror the templates in templates/jinja2/ but are embedded
 * for client-side rendering in the browser.
 */

// eslint-disable-next-line no-unused-vars
const TEMPLATES = {

    // =========================================================================
    // HAProxy Configuration
    // =========================================================================
    "haproxy/haproxy.cfg": `# K3s API Server Load Balancer
# Generated by K3s Configuration Generator
# Deploy to /etc/haproxy/haproxy.cfg on all master nodes

global
    log         /dev/log local0
    log         /dev/log local1 notice
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon
    stats socket /var/lib/haproxy/stats

defaults
    mode                    tcp
    log                     global
    option                  tcplog
    option                  dontlognull
    option                  redispatch
    retries                 3
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout check           10s
    maxconn                 3000

#---------------------------------------------------------------------
# Statistics - accessible at http://<master-ip>:{{ haproxy.stats_port }}/stats
#---------------------------------------------------------------------
listen stats
    bind *:{{ haproxy.stats_port }}
    mode http
    stats enable
    stats uri /stats
    stats refresh 10s
    stats auth {{ haproxy.stats_user }}:{{ haproxy.stats_password }}

#---------------------------------------------------------------------
# K3s API Server Frontend
#---------------------------------------------------------------------
frontend k3s_api_frontend
    bind *:{{ haproxy.frontend_port }}
    mode tcp
    option tcplog
    default_backend k3s_api_backend

#---------------------------------------------------------------------
# K3s API Server Backend
#---------------------------------------------------------------------
backend k3s_api_backend
    mode tcp
    option tcp-check
    balance roundrobin
    default-server inter 10s downinter 5s rise 2 fall 2 slowstart 60s maxconn 250 maxqueue 256 weight 100

{% for master in masters %}
    server {{ master.hostname }} {{ master.ipv4 }}:{{ k3s.api_port }} check
{% endfor %}
`,

    // =========================================================================
    // Keepalived Configuration (per-node)
    // =========================================================================
    "keepalived.conf": `! Keepalived configuration for {{ node.hostname }}
! Generated by K3s Configuration Generator
! Deploy to /etc/keepalived/keepalived.conf

global_defs {
    router_id K3S_APISERVER
    script_user root
    enable_script_security
}

vrrp_script check_haproxy {
    script "/usr/bin/killall -0 haproxy"
    interval {{ keepalived.check_interval }}
    weight 2
    fall {{ keepalived.fall }}
    rise {{ keepalived.rise }}
}

vrrp_instance K3S_VIP {
    state {{ "MASTER" if node_index == 0 else "BACKUP" }}
    interface {{ network.interface }}
    virtual_router_id {{ keepalived.router_id }}
    priority {{ 101 - node_index }}
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass {{ keepalived.auth_pass }}
    }

    virtual_ipaddress {
        {{ vip.ipv4 }}/{{ network.subnet_mask_ipv4 }} dev {{ network.interface }}
        {{ vip.ipv6 }}/{{ network.subnet_mask_ipv6 }} dev {{ network.interface }}
    }

    track_script {
        check_haproxy
    }
}
`,

    // =========================================================================
    // K3s Server Configuration (per-node)
    // =========================================================================
    "k3s-server.yaml": `# K3s Server Configuration for {{ node.hostname }}
# Generated by K3s Configuration Generator
# Deploy to /etc/rancher/k3s/config.yaml
{% if node_index == 0 %}

# First server - initializes the cluster
cluster-init: true
{% else %}

# Additional server - joins existing cluster
server: "https://{{ masters[0].ipv4 }}:{{ k3s.api_port }}"
{% endif %}

# Cluster authentication token
token: "{{ k3s.token or 'GENERATE_TOKEN_AT_DEPLOY_TIME' }}"

# TLS Subject Alternative Names
tls-san:
  - "{{ vip.ipv4 }}"
  - "{{ vip.ipv6 }}"
  - "{{ vip.hostname }}.{{ network.domain }}"
{% for master in masters %}
  - "{{ master.hostname }}.{{ network.domain }}"
  - "{{ master.hostname }}"
  - "{{ master.ipv4 }}"
{% endfor %}

# Node networking (dual-stack)
node-ip: "{{ node.ipv4 }},{{ node.ipv6 }}"
advertise-address: "{{ node.ipv4 }}"

# Cluster CIDR (dual-stack)
cluster-cidr: "{{ k3s.cluster_cidr_v4 }},{{ k3s.cluster_cidr_v6 }}"
service-cidr: "{{ k3s.service_cidr_v4 }},{{ k3s.service_cidr_v6 }}"

# Disabled default components
disable:
{% for component in k3s.disable %}
  - "{{ component }}"
{% endfor %}

# Kubeconfig
write-kubeconfig-mode: "0644"

# etcd
etcd-expose-metrics: true

# API server arguments
kube-apiserver-arg:
  - "advertise-address={{ node.ipv4 }}"
`,

    // =========================================================================
    // K3s Agent Configuration (per-node)
    // =========================================================================
    "k3s-agent.yaml": `# K3s Agent Configuration for {{ node.hostname }}
# Generated by K3s Configuration Generator
# Deploy to /etc/rancher/k3s/config.yaml

# Connect to K3s API via the VIP (HAProxy load balanced)
server: "https://{{ vip.ipv4 }}:{{ haproxy.frontend_port }}"

# Cluster authentication token
token: "{{ k3s.token or 'GENERATE_TOKEN_AT_DEPLOY_TIME' }}"

# Node networking (dual-stack)
node-ip: "{{ node.ipv4 }},{{ node.ipv6 }}"

# Node labels
node-label:
  - "node-role.kubernetes.io/worker=worker"
`,

    // =========================================================================
    // DHCPv4 Static Leases
    // =========================================================================
    "network/dhcpd4-leases.conf": `# ISC DHCP Server - DHCPv4 Static Leases for K3s Cluster
# Generated by K3s Configuration Generator
# Include in dhcpd.conf: include "/etc/dhcp/k3s-leases.conf";

group k3s-cluster {
    option domain-name "{{ network.domain }}";
    option domain-name-servers {{ network.dns_servers[0] }};
    option routers {{ network.gateway_ipv4 }};
    default-lease-time {{ dhcp.default_lease_time }};
    max-lease-time {{ dhcp.max_lease_time }};

    # Master Nodes
{% for master in masters %}
    host {{ master.hostname }} {
        hardware ethernet {{ master.mac }};
        fixed-address {{ master.ipv4 }};
        option host-name "{{ master.hostname }}";
    }

{% endfor %}
    # Worker Nodes
{% for worker in workers %}
    host {{ worker.hostname }} {
        hardware ethernet {{ worker.mac }};
        fixed-address {{ worker.ipv4 }};
        option host-name "{{ worker.hostname }}";
    }

{% endfor %}
}

# VIP Reservation (prevent dynamic assignment)
host k3s-vip-reservation {
    hardware ethernet 00:00:00:00:00:00;
    fixed-address {{ vip.ipv4 }};
    option host-name "{{ vip.hostname }}";
}
`,

    // =========================================================================
    // DHCPv6 Static Leases
    // =========================================================================
    "network/dhcpd6-leases.conf": `# ISC DHCP Server - DHCPv6 Static Leases for K3s Cluster
# Generated by K3s Configuration Generator
# Include in dhcpd6.conf: include "/etc/dhcp/k3s-leases6.conf";

group k3s-cluster-v6 {
    option dhcp6.domain-search "{{ network.domain }}";

    # Master Nodes
{% for master in masters %}
    host {{ master.hostname }} {
        host-identifier option dhcp6.client-id {{ master.duid }};
        fixed-address6 {{ master.ipv6 }};
    }

{% endfor %}
    # Worker Nodes
{% for worker in workers %}
    host {{ worker.hostname }} {
        host-identifier option dhcp6.client-id {{ worker.duid }};
        fixed-address6 {{ worker.ipv6 }};
    }

{% endfor %}
}
`,

    // =========================================================================
    // dnsmasq Static Leases
    // =========================================================================
    "network/dnsmasq-leases.conf": `# dnsmasq Static DHCP Leases for K3s Cluster
# Generated by K3s Configuration Generator

# DHCPv4 Static Leases
{% for master in masters %}
dhcp-host={{ master.mac }},{{ master.ipv4 }},{{ master.hostname }},infinite
{% endfor %}
{% for worker in workers %}
dhcp-host={{ worker.mac }},{{ worker.ipv4 }},{{ worker.hostname }},infinite
{% endfor %}

# DHCPv6 Static Leases
{% for master in masters %}
dhcp-host=id:{{ master.duid }},[{{ master.ipv6 }}],{{ master.hostname }},infinite
{% endfor %}
{% for worker in workers %}
dhcp-host=id:{{ worker.duid }},[{{ worker.ipv6 }}],{{ worker.hostname }},infinite
{% endfor %}

# DNS Records
address=/{{ vip.hostname }}.{{ network.domain }}/{{ vip.ipv4 }}
address=/{{ vip.hostname }}.{{ network.domain }}/{{ vip.ipv6 }}
{% for master in masters %}
address=/{{ master.hostname }}.{{ network.domain }}/{{ master.ipv4 }}
address=/{{ master.hostname }}.{{ network.domain }}/{{ master.ipv6 }}
{% endfor %}
{% for worker in workers %}
address=/{{ worker.hostname }}.{{ network.domain }}/{{ worker.ipv4 }}
address=/{{ worker.hostname }}.{{ network.domain }}/{{ worker.ipv6 }}
{% endfor %}
`,

    // =========================================================================
    // /etc/hosts
    // =========================================================================
    "network/hosts": `# /etc/hosts entries for K3s Cluster
# Generated by K3s Configuration Generator
# Append to /etc/hosts on all cluster nodes.

# K3s API Virtual IP (IPv4 + IPv6)
{{ vip.ipv4 }}    {{ vip.hostname }}.{{ network.domain }} {{ vip.hostname }}
{{ vip.ipv6 }}    {{ vip.hostname }}.{{ network.domain }} {{ vip.hostname }}

# Master nodes
{% for master in masters %}
{{ master.ipv4 }}    {{ master.hostname }}.{{ network.domain }} {{ master.hostname }}
{{ master.ipv6 }}    {{ master.hostname }}.{{ network.domain }} {{ master.hostname }}
{% endfor %}

# Worker nodes
{% for worker in workers %}
{{ worker.ipv4 }}    {{ worker.hostname }}.{{ network.domain }} {{ worker.hostname }}
{{ worker.ipv6 }}    {{ worker.hostname }}.{{ network.domain }} {{ worker.hostname }}
{% endfor %}
`,

    // =========================================================================
    // Sysctl Configuration
    // =========================================================================
    "os/sysctl-k3s.conf": `# Kernel parameters for K3s nodes
# Generated by K3s Configuration Generator
# Deploy to /etc/sysctl.d/90-k3s.conf

# IPv4 forwarding
net.ipv4.ip_forward = 1

# IPv6 forwarding
net.ipv6.conf.all.forwarding = 1

# CRITICAL: Accept Router Advertisements even with forwarding enabled.
# Without this (value=2), enabling forwarding causes the kernel to ignore RAs,
# which breaks SLAAC and DHCPv6 address acquisition.
net.ipv6.conf.all.accept_ra = 2
net.ipv6.conf.default.accept_ra = 2
net.ipv6.conf.{{ network.interface }}.accept_ra = 2

# Bridge networking
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1

# Increase inotify limits
fs.inotify.max_user_instances = 524288
fs.inotify.max_user_watches = 524288

# Increase conntrack table size
net.netfilter.nf_conntrack_max = 131072

# HAProxy non-local bind (master nodes only)
net.ipv4.ip_nonlocal_bind = 1
net.ipv6.ip_nonlocal_bind = 1
`,

    // =========================================================================
    // Variables YAML (for reference / use with Python generator)
    // =========================================================================
    "variables.yaml": `# K3s Cluster Variables
# Generated by K3s Configuration Generator
# Use with: python3 generate.py --vars variables.yaml

os:
  distribution: "{{ os.distribution }}"

network:
  interface: "{{ network.interface }}"
  domain: "{{ network.domain }}"
  dns_servers:
    - "{{ network.dns_servers[0] }}"
  gateway_ipv4: "{{ network.gateway_ipv4 }}"
  subnet_mask_ipv4: {{ network.subnet_mask_ipv4 }}
  subnet_mask_ipv6: {{ network.subnet_mask_ipv6 }}
  ipv6_mode: "{{ network.ipv6_mode }}"

vip:
  ipv4: "{{ vip.ipv4 }}"
  ipv6: "{{ vip.ipv6 }}"
  hostname: "{{ vip.hostname }}"

masters:
{% for master in masters %}
  - hostname: "{{ master.hostname }}"
    ipv4: "{{ master.ipv4 }}"
    ipv6: "{{ master.ipv6 }}"
    mac: "{{ master.mac }}"
    duid: "{{ master.duid }}"
{% endfor %}

workers:
{% for worker in workers %}
  - hostname: "{{ worker.hostname }}"
    ipv4: "{{ worker.ipv4 }}"
    ipv6: "{{ worker.ipv6 }}"
    mac: "{{ worker.mac }}"
    duid: "{{ worker.duid }}"
{% endfor %}

k3s:
  version: "{{ k3s.version }}"
  token: "{{ k3s.token }}"
  api_port: {{ k3s.api_port }}
  disable:
{% for component in k3s.disable %}
    - "{{ component }}"
{% endfor %}
  cluster_cidr_v4: "{{ k3s.cluster_cidr_v4 }}"
  cluster_cidr_v6: "{{ k3s.cluster_cidr_v6 }}"
  service_cidr_v4: "{{ k3s.service_cidr_v4 }}"
  service_cidr_v6: "{{ k3s.service_cidr_v6 }}"

haproxy:
  frontend_port: {{ haproxy.frontend_port }}
  stats_port: {{ haproxy.stats_port }}
  stats_user: "{{ haproxy.stats_user }}"
  stats_password: "{{ haproxy.stats_password }}"

keepalived:
  router_id: {{ keepalived.router_id }}
  auth_pass: "{{ keepalived.auth_pass }}"
  check_interval: 2
  fall: 3
  rise: 2

dhcp:
  default_lease_time: {{ dhcp.default_lease_time }}
  max_lease_time: {{ dhcp.max_lease_time }}
`
};
